### ISSUE TITLE
（develepent）copy your's project,but have a error  

### ISSUE THREAD

**Issue by TinkerDeng** [hahoocn/react-mobile-boilerplate#9]

**Comment by TinkerDeng** [comment]
D:\wamp\www\demo\react-mobile-boilerplate\src\containers\Home\Home.js
  31:2   error  Unexpected tab character                                                             no-tabs
  31:2   error  Expected indentation of 2 spaces but found 1 tab                                     indent
  31:6   error  Expected 'this' to be used by class method 'show'                                    class-methods-use-this
  31:8   error  Missing space before opening brace                                                   space-before-blocks
  32:2   error  Unexpected tab character                                                             no-tabs
  32:3   error  Expected indentation of 2 spaces but found 2 tabs                                    indent
  32:9   error  Strings must use singlequote                                                         quotes
  33:2   error  Expected indentation of 0 spaces but found 1 tab                                     indent
  33:2   error  Unexpected tab character                                                             no-tabs
  35:5   error  Expected empty line after require statement not followed by another require          import/newline-after-import
  46:9   error  Visible, non-interactive elements should not have mouse or keyboard event listeners  jsx-a11y/no-static-element-interactions
  46:13  error  JSX props should not use .bind()                                                     react/jsx-no-bind
  46:22  error  JSX props should not use .bind()                                                     react/jsx-no-bind

✖ 13 problems (13 errors, 0 warnings)

**Comment by TinkerDeng** [comment]
In production environment is well,But in  development environment,have this error . when i change a little,Just wrap，can‘t upload a img， so please  help  me？（生产环境没啥问题，开发环境的时候不能改，随便加个空格它都报错，我想问一下怎么解决）

**Comment by ihahoo** [comment]
.eslintrc defines the "indent": [2, 2, {"SwitchCase": 1}] rules. 
http://eslint.org/docs/rules/indent.html

.editorconfig defines two spaces instead of tab, set the editor tab key to the corresponding two spaces, or to allow the editor to support editorconfig, will automatically set.
http://editorconfig.org/

(为了编码格式统一，这里缩进用了2个空格的格式，不是直接tab符，eslint的indent规则有对这个验证，当然你也可以直接设置规则去掉这个验证，这样就不会显示这个错误了。在.editorconfig中，设置了编辑器的规则，也是2个空格，你使用什么编辑器？如果支持editorconfig的编辑器或者插件，安装好后，编辑器会自动按照这个规则当缩进的时候是2个空格而不是tab，比如atom中安装了editorconfig的插件，就自动按照项目中.editorconfig的规则执行了。另外，编辑器最好可以安装支持eslint的的插件，这样在编码的时候就会自动提示错误或者格式错误，而这个错误规则都可以通过.eslintrc中设置，比如我使用atom安装了linter和linter-eslint)

**Comment by ihahoo** [comment]
ESLint set the rules of the airbnb, please refer to the specific ESLint and Airbnb React/JSX Style Guide
http://eslint.org/
https://github.com/airbnb/javascript/tree/master/react
https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb

(具体参考ESLint，这里使用了airbnb的React/JSX规则，所以你上面贴的错误中有相应规则的报错，如果你的编辑器支持ESLint，在相应错误提示处，可以直接点开链接，查看具体的规则内容，当然你可以按照自己的习惯直接修改.eslintrc中的规则，不再提示错误或者改成提示警报而不是错误)

**Comment by TinkerDeng** [comment]
太感谢了  谢谢
